{player setVariable ["ace_w_head_hit",_this];},
{player setVariable ["ace_w_body",_this];},
{player setVariable ["ace_w_hands",_this];},
{player setVariable ["ace_w_legs",_this];},
{player setVariable ["ace_w_state",_this];},
{player setVariable ["ace_sys_wounds_uncon", _this, true];},
{player setVariable ["ace_w_bleed",_this];},
{player setVariable ["ace_w_bleed_add",_this];},
{player setVariable ["ace_w_pain",_this];},
{player setVariable ["ace_w_pain_add",_this];},
{player setVariable ["ace_w_epi",_this];},
{player setVariable ["ace_w_nextuncon", _this];},
{player setVariable ["ace_w_unconlen", _this];},
{player setVariable ["ace_w_stab", _this];},
{player setVariable ["ace_w_cutofftime", _this];},
{player setVariable ["ace_w_carry", _this, true];},
{player setVariable ["ace_w_revive", _this];},
{player setVariable ["ace_w_wakeup", _this];},